#!/bin/bash
if [ $1 = "-d" ]; then
  shift
  ./bin/lexer $* > lexer.out
  gdb -ex "set args $* < lexer.out" ./parser
# sadly i can't find the source to build the real reference parser
#elif [ $1 = "-r" ]; then
#  shift
#  /usr/class/cs143/bin/reflexer $* | /usr/class/cs143/bin/refparser $* 
else
  ./bin/lexer $* | ./bin/parser $*
fi
